[2022-12-16 21:06:26,972] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: process_web_log.extract_data manual__2022-12-16T21:06:26.195896+00:00 [queued]>
[2022-12-16 21:06:26,982] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: process_web_log.extract_data manual__2022-12-16T21:06:26.195896+00:00 [queued]>
[2022-12-16 21:06:26,982] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 21:06:26,982] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-16 21:06:26,982] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 21:06:26,996] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): extract_data> on 2022-12-16 21:06:26.195896+00:00
[2022-12-16 21:06:27,001] {standard_task_runner.py:52} INFO - Started process 186 to run task
[2022-12-16 21:06:27,005] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'process_web_log', 'extract_data', 'manual__2022-12-16T21:06:26.195896+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/process_web_log.py', '--cfg-path', '/tmp/tmp9mlh6rxx', '--error-file', '/tmp/tmpc3h8nqnc']
[2022-12-16 21:06:27,005] {standard_task_runner.py:80} INFO - Job 25: Subtask extract_data
[2022-12-16 21:06:27,045] {task_command.py:369} INFO - Running <TaskInstance: process_web_log.extract_data manual__2022-12-16T21:06:26.195896+00:00 [running]> on host b3fdf538c244
[2022-12-16 21:06:27,122] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=process_web_log
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-16T21:06:26.195896+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-16T21:06:26.195896+00:00
[2022-12-16 21:06:27,123] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-12-16 21:06:27,123] {subprocess.py:74} INFO - Running command: ['bash', '-c', "grep -o '[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}' echo /home/aliabusaleh/Downloads/assignemnt_4/dags/the_log/log.txt > ./home/aliabusaleh/Downloads/assignemnt_4/dags/the_log/extracted_data.txt"]
[2022-12-16 21:06:27,134] {subprocess.py:85} INFO - Output:
[2022-12-16 21:06:27,136] {subprocess.py:92} INFO - bash: line 1: ./home/aliabusaleh/Downloads/assignemnt_4/dags/the_log/extracted_data.txt: No such file or directory
[2022-12-16 21:06:27,136] {subprocess.py:96} INFO - Command exited with return code 1
[2022-12-16 21:06:27,158] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-16 21:06:27,162] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=process_web_log, task_id=extract_data, execution_date=20221216T210626, start_date=20221216T210626, end_date=20221216T210627
[2022-12-16 21:06:27,176] {standard_task_runner.py:97} ERROR - Failed to execute job 25 for task extract_data (Bash command failed. The command returned a non-zero exit code 1.; 186)
[2022-12-16 21:06:27,216] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-16 21:06:27,252] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
